# Generated by Django 4.1.7 on 2023-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("continent", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("ethnicity", models.CharField(max_length=50)),
            ],
        ),
    ]
